

export const SCHEDULE_BY_ID = "SCHEDULE_BY_ID"
export const SCHEDULE_BY_ID_SUCCESS = "SCHEDULE_BY_ID_SUCCESS"
export const SCHEDULE_BY_ID_FAILURE = "SCHEDULE_BY_ID_FAILURE"
export const ALL_SCHEDULES = "ALL_SCHEDULES"
export const ALL_SCHEDULES_SUCCESS = "ALL_SCHEDULES_SUCCESS"
export const ALL_SCHEDULES_FAILURE = "ALL_SCHEDULES_FAILURE"
export const ALL_RESPONSES = "ALL_RESPONSES"
export const ALL_RESPONSES_SUCCESS = "ALL_RESPONSES_SUCCESS"
export const ALL_RESPONSES_FAILURE = "ALL_RESPONSES_FAILURE"
export const ALL_USER_SCHEDULES = "ALL_USER_SCHEDULES"
export const ALL_USER_SCHEDULES_SUCCESS = "ALL_USER_SCHEDULES_SUCCESS"
export const ALL_USER_SCHEDULES_FAILURE = "ALL_USER_SCHEDULES_FAILURE"
export const ERROR_MSG = 'ERROR_MSG'
export const SUCCESS_MSG = 'SUCCESS_MSG'